object Versions {
    const val agp = "8.1.0"
    const val kotlin = "1.9.20"
    const val compose = "1.5.10"
    const val ktor = "2.3.5"
    const val serialization = "1.6.0"
    const val koin = "3.5.0"
    const val datetime = "0.4.1"
    const val kamel = "0.8.2"
    const val core_ktx = "1.12.0"
    const val accompanist = "0.21.0-beta"
    const val compose_navigation = "2.7.4"
    const val compose_activity = "1.8.0"
    const val appcompat = "1.6.1"
    const val coroutines = "1.7.3"
    const val exif = "1.3.6"
    const val korlibs = "4.0.10"
}